import type {Metadata} from 'next'
import './globals.css'
import {Header} from "@/app/components/blocks/Header";
import {Footer} from "@/app/components/blocks/Footer";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <Header/>
    <main>{children}</main>
    <Footer/>
    </body>
    </html>
  )
}
